FROM ubuntu:18.04

# Install dependencies
# ====================
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  ca-certificates \
  cmake \
  curl \
  unzip

# Install Libtorch - CPU
#=======================
WORKDIR /
RUN curl https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.7.0%2Bcpu.zip --output libtorch.zip \
    && unzip libtorch.zip -d usr/local/lib \
    && rm libtorch.zip

RUN ldconfig

ENV GOTCH_LIBTORCH="/usr/local/lib/libtorch"
ENV LIBTORCH="/usr/local/lib/libtorch"
ENV LIBRARY_PATH="$GOTCH_LIBTORCH/lib"
ENV CPATH="$GOTCH_LIBTORCH/lib:$GOTCH_LIBTORCH/include:$GOTCH_LIBTORCH/include/torch/csrc/api/include"
ENV LD_LIBRARY_PATH="$GOTCH_LIBTORCH/lib"

